---

- hosts: gluster4-servers
  become: true
  tasks:
    - name: Stop glusterd2
      systemd:
        name: glusterd2
        state: stopped
    - name: Remove store data
      file:
        path: /usr/local/var/lib/glusterd2/store
        state: absent
    - name: Remove run files
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /usr/local/var/run/glusterd2/glusterd2.pid
        - /usr/local/var/run/glusterd2/glusterd2.socket
    - name: Start glusterd2
      systemd:
        name: glusterd2
        daemon_reload: yes
        state: started
